name: Publish to SVN

on:
  [push,workflow_dispatch] 


jobs:
  checkout_svn:
    if : github.ref_type == 'tag' 
    runs-on: ubuntu-latest

    env:
      REPO_NAME: ''

    steps:
      - uses: actions/checkout@v2
      - name: Set env variables
        run: |
          REPO_NAME=$(basename $GITHUB_REPOSITORY)

          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$GITHUB_REF_NAME" >> $GITHUB_ENV

      - name: Install SVN
        run: sudo apt-get update && sudo apt-get install -y subversion

      - name: Checkout SVN repository
        run: |  
          echo $REPO_NAME
          svn co --username=${{ secrets.SVN_USERNAME }} --password=${{ secrets.SVN_PASSWORD }} ${{ secrets.SVN_URL }}  $REPO_NAME
          echo "list content repo name:"
          ls -al $REPO_NAME
          echo "list content trunk in repo_name"
          ls -al $REPO_NAME/trunk/
          echo "list content branches in repo_name"
          ls -al $REPO_NAME/branches/
          echo "list content tags in repo_name"
          ls -al $REPO_NAME/tags/
          echo "list content assets in repo_name"
          ls -al $REPO_NAME/assets/
          echo "list content ./ in runner "
          ls -al ./

      - name: Copy trunk && tag
        run: |
          rm -rf $REPO_NAME/trunk/*
          rsync -av --exclude="$REPO_NAME" --exclude=".git" --exclude=".github/" ./ $REPO_NAME/trunk
          #svn copy $REPO_NAME/trunk/ $REPO_NAME/tags/$RELEASE_VERSION
          echo "list content trunk in repo_name post rsync"
          ls -al $REPO_NAME/trunk
          #svn stat $REPO_NAME
          svn import --username=${{ secrets.SVN_USERNAME }} --password=${{ secrets.SVN_PASSWORD }} $REPO_NAME -m "deploy"
          svn update
